// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do one of these:
//
//    using Models;
//
//    var extractionRequest = ExtractionRequest.FromJson(jsonString);
//    var extractionMetadataResponse = ExtractionMetadataResponse.FromJson(jsonString);
//    var exportRequest = ExportRequest.FromJson(jsonString);
//    var activateRequest = ActivateRequest.FromJson(jsonString);
//    var bootRequest = BootRequest.FromJson(jsonString);
#nullable enable
#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8603

namespace Models
{
    using System;
    using System.Collections.Generic;

    using System.Text.Json;
    using System.Text.Json.Serialization;
    using System.Globalization;

    public partial class ExtractionRequest
    {
        /// <summary>
        /// The absolute path to the source image file
        /// </summary>
        [JsonPropertyName("source_path")]
        public string SourcePath { get; set; }
    }

    public partial class ExtractionMetadataResponse
    {
        [JsonPropertyName("bboxes")]
        public long[][] Bboxes { get; set; }

        [JsonPropertyName("hardware_mode_used")]
        public string HardwareModeUsed { get; set; }

        [JsonPropertyName("layers_extracted")]
        public long LayersExtracted { get; set; }

        [JsonPropertyName("localized_coordinates")]
        public LocalizedCoordinate[] LocalizedCoordinates { get; set; }

        [JsonPropertyName("message")]
        public string Message { get; set; }

        [JsonPropertyName("output_paths")]
        public string[] OutputPaths { get; set; }

        [JsonPropertyName("source_path")]
        public string SourcePath { get; set; }

        [JsonPropertyName("status")]
        public string Status { get; set; }
    }

    public partial class LocalizedCoordinate
    {
        [JsonPropertyName("height")]
        public long Height { get; set; }

        [JsonPropertyName("width")]
        public long Width { get; set; }

        [JsonPropertyName("x")]
        public long X { get; set; }

        [JsonPropertyName("y")]
        public long Y { get; set; }
    }

    public partial class ExportRequest
    {
        /// <summary>
        /// The absolute path to the destination folder chosen by the user
        /// </summary>
        [JsonPropertyName("destination_folder")]
        public string DestinationFolder { get; set; }

        /// <summary>
        /// An array of requested export formats
        /// </summary>
        [JsonPropertyName("formats")]
        public Format[] Formats { get; set; }
    }

    public partial class ActivateRequest
    {
        /// <summary>
        /// The Supabase JWT returned upon successful login.
        /// </summary>
        [JsonPropertyName("jwt")]
        public string Jwt { get; set; }

        /// <summary>
        /// The unique hardware identifier of the machine.
        /// </summary>
        [JsonPropertyName("machine_id")]
        public string MachineId { get; set; }
    }

    public partial class BootRequest
    {
        /// <summary>
        /// The Supabase JWT to verify for boot authorization.
        /// </summary>
        [JsonPropertyName("jwt")]
        public string Jwt { get; set; }

        /// <summary>
        /// The unique hardware identifier of the machine.
        /// </summary>
        [JsonPropertyName("machine_id")]
        public string MachineId { get; set; }
    }

    public enum Format { Png, Psd, Svg, TiffCmyk, TiffRgb };

    public partial class ExtractionRequest
    {
        public static ExtractionRequest FromJson(string json) => JsonSerializer.Deserialize<ExtractionRequest>(json, Models.Converter.Settings);
    }

    public partial class ExtractionMetadataResponse
    {
        public static ExtractionMetadataResponse FromJson(string json) => JsonSerializer.Deserialize<ExtractionMetadataResponse>(json, Models.Converter.Settings);
    }

    public partial class ExportRequest
    {
        public static ExportRequest FromJson(string json) => JsonSerializer.Deserialize<ExportRequest>(json, Models.Converter.Settings);
    }

    public partial class ActivateRequest
    {
        public static ActivateRequest FromJson(string json) => JsonSerializer.Deserialize<ActivateRequest>(json, Models.Converter.Settings);
    }

    public partial class BootRequest
    {
        public static BootRequest FromJson(string json) => JsonSerializer.Deserialize<BootRequest>(json, Models.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this ExtractionRequest self) => JsonSerializer.Serialize(self, Models.Converter.Settings);
        public static string ToJson(this ExtractionMetadataResponse self) => JsonSerializer.Serialize(self, Models.Converter.Settings);
        public static string ToJson(this ExportRequest self) => JsonSerializer.Serialize(self, Models.Converter.Settings);
        public static string ToJson(this ActivateRequest self) => JsonSerializer.Serialize(self, Models.Converter.Settings);
        public static string ToJson(this BootRequest self) => JsonSerializer.Serialize(self, Models.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerOptions Settings = new(JsonSerializerDefaults.General)
        {
            Converters =
            {
                FormatConverter.Singleton,
                new DateOnlyConverter(),
                new TimeOnlyConverter(),
                IsoDateTimeOffsetConverter.Singleton
            },
        };
    }

    internal class FormatConverter : JsonConverter<Format>
    {
        public override bool CanConvert(Type t) => t == typeof(Format);

        public override Format Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "PNG":
                    return Format.Png;
                case "PSD":
                    return Format.Psd;
                case "SVG":
                    return Format.Svg;
                case "TIFF_CMYK":
                    return Format.TiffCmyk;
                case "TIFF_RGB":
                    return Format.TiffRgb;
            }
            throw new Exception("Cannot unmarshal type Format");
        }

        public override void Write(Utf8JsonWriter writer, Format value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case Format.Png:
                    JsonSerializer.Serialize(writer, "PNG", options);
                    return;
                case Format.Psd:
                    JsonSerializer.Serialize(writer, "PSD", options);
                    return;
                case Format.Svg:
                    JsonSerializer.Serialize(writer, "SVG", options);
                    return;
                case Format.TiffCmyk:
                    JsonSerializer.Serialize(writer, "TIFF_CMYK", options);
                    return;
                case Format.TiffRgb:
                    JsonSerializer.Serialize(writer, "TIFF_RGB", options);
                    return;
            }
            throw new Exception("Cannot marshal type Format");
        }

        public static readonly FormatConverter Singleton = new FormatConverter();
    }

    public class DateOnlyConverter : JsonConverter<DateOnly>
    {
        private readonly string serializationFormat;
        public DateOnlyConverter() : this(null) { }

        public DateOnlyConverter(string? serializationFormat)
        {
                this.serializationFormat = serializationFormat ?? "yyyy-MM-dd";
        }

        public override DateOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                var value = reader.GetString();
                return DateOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, DateOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    public class TimeOnlyConverter : JsonConverter<TimeOnly>
    {
        private readonly string serializationFormat;

        public TimeOnlyConverter() : this(null) { }

        public TimeOnlyConverter(string? serializationFormat)
        {
                this.serializationFormat = serializationFormat ?? "HH:mm:ss.fff";
        }

        public override TimeOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                var value = reader.GetString();
                return TimeOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, TimeOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    internal class IsoDateTimeOffsetConverter : JsonConverter<DateTimeOffset>
    {
        public override bool CanConvert(Type t) => t == typeof(DateTimeOffset);

        private const string DefaultDateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK";

        private DateTimeStyles _dateTimeStyles = DateTimeStyles.RoundtripKind;
        private string? _dateTimeFormat;
        private CultureInfo? _culture;

        public DateTimeStyles DateTimeStyles
        {
                get => _dateTimeStyles;
                set => _dateTimeStyles = value;
        }

        public string? DateTimeFormat
        {
                get => _dateTimeFormat ?? string.Empty;
                set => _dateTimeFormat = (string.IsNullOrEmpty(value)) ? null : value;
        }

        public CultureInfo Culture
        {
                get => _culture ?? CultureInfo.CurrentCulture;
                set => _culture = value;
        }

        public override void Write(Utf8JsonWriter writer, DateTimeOffset value, JsonSerializerOptions options)
        {
                string text;


                if ((_dateTimeStyles & DateTimeStyles.AdjustToUniversal) == DateTimeStyles.AdjustToUniversal
                        || (_dateTimeStyles & DateTimeStyles.AssumeUniversal) == DateTimeStyles.AssumeUniversal)
                {
                        value = value.ToUniversalTime();
                }

                text = value.ToString(_dateTimeFormat ?? DefaultDateTimeFormat, Culture);

                writer.WriteStringValue(text);
        }

        public override DateTimeOffset Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                string? dateText = reader.GetString();

                if (string.IsNullOrEmpty(dateText) == false)
                {
                        if (!string.IsNullOrEmpty(_dateTimeFormat))
                        {
                                return DateTimeOffset.ParseExact(dateText, _dateTimeFormat, Culture, _dateTimeStyles);
                        }
                        else
                        {
                                return DateTimeOffset.Parse(dateText, Culture, _dateTimeStyles);
                        }
                }
                else
                {
                        return default(DateTimeOffset);
                }
        }


        public static readonly IsoDateTimeOffsetConverter Singleton = new IsoDateTimeOffsetConverter();
    }
}
#pragma warning restore CS8618
#pragma warning restore CS8601
#pragma warning restore CS8603
